### ISSUE TITLE
invalid literal for int() with base 10

### ISSUE THREAD

**Issue by farhaan23** [llSourcell/predicting_stock_prices#10]
Traceback (most recent call last):
  File "farhaan.py", line 45, in <module>
    get_data('aapl.csv')
  File "farhaan.py", line 19, in get_data
    dates.append(int(row[0].split('-')[0]))
ValueError: invalid literal for int() with base 10: '14:54'

Help pls

**Comment by ghost** [comment]
Try:
dates.append(int(row[0].split('/')[0]))

The 'split' is looking for a date with '-' and not '/'. E.g. 01-01-2019
Yahoo data is normally this way 01/01/2019, however other data sets may have '-'

**Comment by aswinr22** [comment]
There is a decimal number in your CSV 'date' column, you need to change it manually to integer
